name: CI
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:

  setup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v1.7.2
        with:
          dotnet-version: 5.0.x
          
  restore:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - name: Restore
        run: dotnet restore

  test:
    runs-on: ubuntu-latest
    needs: restore
    steps:
      - name: Test
        run: dotnet test

  publish:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Publish
        run: dotnet publish -c Release -r linux-x64 --self-contained false
  
  deploy:
    runs-on: ubuntu-latest
    needs: publish
    steps:
      - name: Deploy
        run: |
          ls .
          echo TODO deploy
