name: CI
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:

  build:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - uses: actions/checkout@v2
      - name: Build
        uses: actions/setup-dotnet@v1.7.2
        run: dotnet build

  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v2
      - name: Test
        uses: actions/setup-dotnet@v1.7.2
        run: dotnet test

  deploy:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v2
      - name: Publish
        uses: actions/setup-dotnet@v1.7.2
        run: |
          dotnet publish -c Release -r linux-x64 --self-contained false
          ls .
          echo TODO deploy
